### ISSUE TITLE
Return error code in ability check response

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/MAVN.Service.PartnerManagement#22]
In https://github.com/OpenMAVN/MAVN.Service.PartnerManagement/blob/master/client/MAVN.Service.PartnerManagement.Client/Models/Partner/CheckAbilityResponse.cs
we need to return enum ErrorCode instead of string InabilityReason, so it can be translated to a proper string on the frontend.

**Comment by HannaAndreevna** [comment]
+

**Comment by starkmsu** [comment]
Implemented in linked PR
